Add reviewers POST API for adding reviewrs to a PR (WIP)
vermiculus/ghub-plus pull request #11
Opened 2018-09-14 20:14 UTC by bobrowadam

2018-09-15 00:19 UTC, vermiculus commented
Why was this closed?

2018-09-15 01:06 UTC, bobrowadam commented
I just noticed that its already implemented...

2018-09-15 01:10 UTC, vermiculus commented
`/repos/:owner/:repo/collaborators` wasn't, but I can add that back in. Thanks anyway!

2018-09-15 01:40 UTC, bobrowadam commented
Oh right!
Ok so I'll open it again after I'll test the magithub change I did. Will proceed tomorrow (its 4 am over here...)

2018-09-16 01:29 UTC, vermiculus commented on ghub+.el
> +
Looks like a spurious change

2018-09-16 01:30 UTC, vermiculus commented on ghub+.el
> +  "List colaborators.
`colaborators` => `collaborators` :-) (ditto for below)

2018-09-16 01:33 UTC, vermiculus requested changes
Changes look good! Just a few notes.

Can you squash and rebase onto the current `master`?

2018-09-16 06:10 UTC, bobrowadam commented
Squashed and rebased on `master`.

2018-10-21 22:56 UTC, vermiculus approved these changes

2018-10-21 23:02 UTC, vermiculus approved these changes

2018-10-21 23:03 UTC, vermiculus commented
I don't know what's going on with review approval (I can't even approve manually via the API), so… 'approved'. :-)

2018-10-21 23:06 UTC, merged